### ISSUE TITLE
Error when converting from gpuArray to double in `extract_and_filter`

### ISSUE THREAD

**Issue by eturkes** [jduffield65/iss#11]
Hi, I'm not sure if the GPU features in `extract_and_filter` are complete yet, but I run into the error in the screenshot on the PixelBased branch. I'm not too familiar with GPU processing so not sure if this is specific to my system. I figured I'd let you know in case you are having success with running the code as is. Attached also are some GPU/system info that might help.

![Screenshot from 2020-04-17 22-52-20](https://user-images.githubusercontent.com/25193231/79906117-41a05f00-83e5-11ea-90ae-ebe540ec9d1e.png)

![Screenshot from 2020-04-21 15-24-34](https://user-images.githubusercontent.com/25193231/79906130-46651300-83e5-11ea-90de-481de4420954.png)

**Comment by jduffield65** [comment]
I think I fixed the problem here was that SE was a GPU array and IFS was not, I think I fixed it with the line: [`gather(SE)`](https://github.com/jduffield65/iss/blob/ea7cff9c4a7129ca4631bdd9f35493e6bc8c976f/%40iss/extract_and_filter.m#L196).

**Comment by eturkes** [comment]
Thanks alot! I re-ran everything from the beginning and this fixed it. The process is noticeably quicker with the GPU, so this really helps
